# Generated by Django 3.2.6 on 2023-02-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vulnerablity_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_sheet', models.TextField()),
                ('created_date', models.DateTimeField()),
            ],
        ),
    ]
