# Generated by Django 3.2.6 on 2023-02-04 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerablity_dashboard', '0003_alter_vulnerablity_analyse_data_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vulnerablity_analyse_data',
            name='created_date',
        ),
    ]
