# Generated by Django 3.2.6 on 2023-02-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerablity_dashboard', '0005_vulnerablity_analyse_data_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerablity_analyse_data',
            name='created_date',
            field=models.DateTimeField(),
        ),
    ]
