# Generated by Django 3.2.6 on 2023-04-12 14:35

import apps.vulnerablity_dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vulnerablity_dashboard', '0006_alter_vulnerablity_analyse_data_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerablity_data',
            name='excel_sheet',
            field=models.FileField(upload_to=apps.vulnerablity_dashboard.models.get_upload_file),
        ),
    ]
