# Generated by Django 3.2.6 on 2022-06-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0003_category_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='subname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
