# Generated by Django 3.2.6 on 2021-10-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('system_configuration', '0002_alter_menu_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='access_group',
            field=models.ManyToManyField(blank=True, related_name='accessgroup', to='auth.Group'),
        ),
    ]
