# Generated by Django 3.2.6 on 2022-03-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_configuration', '0006_auto_20211028_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='order',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='menu_category',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
