# Generated by Django 3.2.6 on 2022-03-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_configuration', '0008_alter_menu_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_category',
            name='menu_type',
            field=models.CharField(choices=[('1', 'BLOCK'), ('2', 'STACK'), ('3', 'SINGLE MENU')], default='3', max_length=20),
        ),
    ]
