# Generated by Django 3.2.6 on 2022-03-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_configuration', '0009_menu_category_menu_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='auth_details',
            fields=[
                ('auth_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('auth', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
