# Generated by Django 3.2.6 on 2022-03-21 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system_configuration', '0010_auth_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api_details',
            name='auth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authdtl', to='system_configuration.auth_details'),
        ),
    ]
