# Generated by Django 3.2.6 on 2022-03-21 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_configuration', '0011_alter_api_details_auth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auth_details',
            options={'verbose_name': 'AUTH Detail', 'verbose_name_plural': 'AUTH Details'},
        ),
    ]
