# Generated by Django 3.2.6 on 2022-05-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_configuration', '0012_alter_auth_details_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='api_details',
            options={'ordering': ('auth',), 'verbose_name': 'API Detail', 'verbose_name_plural': 'API Details'},
        ),
        migrations.RemoveField(
            model_name='api_details',
            name='http_address',
        ),
        migrations.AddField(
            model_name='auth_details',
            name='http_address',
            field=models.CharField(default='', max_length=100),
        ),
    ]
