# Generated by Django 3.2.6 on 2022-05-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_configuration', '0013_auto_20220505_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth_details',
            name='key',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='auth_details',
            name='auth',
            field=models.CharField(default='', max_length=250),
        ),
    ]
