# Generated by Django 3.2.6 on 2022-09-25 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('system_configuration', '0016_delete_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.TextField(null=True, unique=True)),
                ('is_live', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('access_group', models.ManyToManyField(blank=True, related_name='accessgroup', to='auth.Group')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menuCategory', to='system_configuration.menu_category')),
            ],
            options={
                'permissions': (('CUSTOM_PERMISSION_VIEW_SYSTEM', 'Custom Access to view system page'),),
            },
        ),
    ]
