# Generated by Django 3.2.6 on 2022-06-27 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spc_cld', '0003_auto_20220523_1729'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uptime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='uptime_time_series_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SID', models.CharField(default='', max_length=3)),
                ('systemNumber', models.CharField(default='', max_length=18)),
                ('DataCenter', models.CharField(default='', max_length=50)),
                ('FromTime', models.DateTimeField(blank=True, default=None)),
                ('ToTime', models.DateTimeField(blank=True, default=None, null=True)),
                ('Status', models.CharField(default='', max_length=30)),
                ('Duration', models.CharField(default='', max_length=80)),
                ('durationInMin', models.BigIntegerField(default=0)),
                ('errorStartTime', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('acknowledgedAt', models.DateTimeField(null=True)),
                ('IsAcknowledged', models.BooleanField(default=False)),
                ('Product_Area', models.CharField(default='S4_PC', max_length=30)),
                ('acknowledgedWithin', models.BigIntegerField(default=0)),
                ('acknowledgedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uptime Time Series',
                'verbose_name_plural': 'Uptime Time Series',
                'ordering': ('SID',),
            },
        ),
        migrations.CreateModel(
            name='uptime_status',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('SID', models.CharField(default='', max_length=30)),
                ('DataCenter', models.CharField(default='', max_length=50)),
                ('created', models.BigIntegerField(null=True)),
                ('name', models.CharField(max_length=300, null=True)),
                ('hostname', models.CharField(max_length=255, null=True)),
                ('resolution', models.IntegerField(null=True)),
                ('verify_certificate', models.BooleanField(default=False)),
                ('lasterrortime', models.BigIntegerField(null=True)),
                ('lasttesttime', models.BigIntegerField(null=True)),
                ('lastresponsetime', models.IntegerField(null=True)),
                ('client', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=255, null=True)),
                ('LastSyncAt', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('dc_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dc_info_uptime', to='spc_cld.datacenter_decs')),
                ('system_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sid_info_uptime', to='spc_cld.system')),
            ],
            options={
                'verbose_name': 'Uptime Status',
                'verbose_name_plural': 'Uptime Status',
                'ordering': ('SID',),
            },
        ),
        migrations.CreateModel(
            name='comment_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SID', models.CharField(max_length=3, null=True)),
                ('DC', models.CharField(max_length=3, null=True)),
                ('comment', models.TextField(null=True)),
                ('expry_date', models.DateTimeField(null=True)),
                ('updated_on', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('comment_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='URLComments_uptime', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ('SID',),
            },
        ),
        migrations.AddIndex(
            model_name='uptime_time_series_data',
            index=models.Index(fields=['SID'], name='uptime_upti_SID_0d5e2e_idx'),
        ),
        migrations.AddIndex(
            model_name='uptime_status',
            index=models.Index(fields=['SID'], name='uptime_upti_SID_eb99f7_idx'),
        ),
        migrations.AddIndex(
            model_name='comment_table',
            index=models.Index(fields=['SID'], name='uptime_comm_SID_fa7427_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='comment_table',
            unique_together={('SID', 'DC')},
        ),
    ]
