# Generated by Django 3.2.6 on 2022-07-06 08:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spc_cld', '0003_auto_20220523_1729'),
        ('uptime', '0002_auto_20220627_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='uptime_status_history',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('SID', models.CharField(default='', max_length=30)),
                ('DataCenter', models.CharField(default='', max_length=50)),
                ('created', models.BigIntegerField(null=True)),
                ('name', models.CharField(max_length=300, null=True)),
                ('hostname', models.CharField(max_length=255, null=True)),
                ('resolution', models.IntegerField(null=True)),
                ('verify_certificate', models.BooleanField(default=False)),
                ('lasterrortime', models.BigIntegerField(null=True)),
                ('lasttesttime', models.BigIntegerField(null=True)),
                ('lastresponsetime', models.IntegerField(null=True)),
                ('client', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=255, null=True)),
                ('LastSyncAt', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('dc_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dc_info_uptime_history', to='spc_cld.datacenter_decs')),
                ('system_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sid_info_uptime_history', to='spc_cld.system')),
            ],
            options={
                'verbose_name': 'Uptime Status History',
                'verbose_name_plural': 'Uptime Status History',
                'ordering': ('SID',),
            },
        ),
        migrations.AddIndex(
            model_name='uptime_status_history',
            index=models.Index(fields=['SID'], name='uptime_upti_SID_f6e34f_idx'),
        ),
    ]
