# Generated by Django 3.2.6 on 2022-07-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uptime', '0003_auto_20220706_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='tempMonitor',
            fields=[
                ('checkID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('SID', models.CharField(default='', max_length=20)),
                ('isDelete', models.BooleanField(default=False)),
                ('ExpryDate', models.DateTimeField(null=True)),
            ],
        ),
    ]
