# Generated by Django 3.2.6 on 2022-06-18 08:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_account', '0048_alter_subteam_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='shift_status',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Shift Status',
                'verbose_name_plural': 'Shift Status',
            },
        ),
        migrations.CreateModel(
            name='task_plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdate', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_account.subteam')),
            ],
            options={
                'verbose_name': 'Task Plan',
                'verbose_name_plural': 'Task Plan',
            },
        ),
        migrations.CreateModel(
            name='shift_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='S1', max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=30, null=True)),
                ('text_color', models.CharField(max_length=30, null=True)),
                ('is_allow_in_preference', models.BooleanField(default=False)),
                ('from_time', models.IntegerField(default=0)),
                ('to_time', models.IntegerField(default=0)),
                ('ordering', models.IntegerField(default=0)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_account.location')),
            ],
            options={
                'verbose_name': 'Shift Type',
                'verbose_name_plural': 'Shift Types',
            },
        ),
        migrations.CreateModel(
            name='shift_temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdate', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('is_shift_locked', models.BooleanField(default=False)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_member_info', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roster.shift_type')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roster.shift_status')),
            ],
            options={
                'verbose_name': 'Shift Roster Temp',
                'verbose_name_plural': 'Shift Roster Temp',
            },
        ),
        migrations.CreateModel(
            name='shift_preferance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_off', models.CharField(blank=True, max_length=40, null=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_preferance_info', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roster.shift_type')),
            ],
            options={
                'verbose_name': 'Shift Preferance',
                'verbose_name_plural': 'Shift Preferances',
            },
        ),
        migrations.CreateModel(
            name='shift_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_month', models.IntegerField(default=0)),
                ('comment', models.CharField(default='', max_length=3000)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_shift_member_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shift Comments',
                'verbose_name_plural': 'Shift Coments',
            },
        ),
        migrations.CreateModel(
            name='shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdate', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('is_shift_locked', models.BooleanField(default=False)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roster.shift_type')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roster.shift_status')),
            ],
            options={
                'verbose_name': 'Shift Roster',
                'verbose_name_plural': 'Shift Roster',
            },
        ),
        migrations.CreateModel(
            name='planned_leave_calander',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdate', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Planned Leave',
                'verbose_name_plural': 'Planned Leave',
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_account.location')),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
            },
        ),
    ]
