# Generated by Django 3.2.6 on 2022-06-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift_type',
            name='from_time',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='shift_type',
            name='to_time',
            field=models.FloatField(default=0),
        ),
    ]
