# Generated by Django 3.2.6 on 2022-06-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0002_auto_20220618_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift_type',
            name='from_time',
        ),
        migrations.RemoveField(
            model_name='shift_type',
            name='to_time',
        ),
        migrations.AddField(
            model_name='shift_type',
            name='time_info',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
