# Generated by Django 3.2.6 on 2022-06-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0003_auto_20220618_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift_type',
            name='is_allow_in_dashboard',
            field=models.BooleanField(default=False),
        ),
    ]
