# Generated by Django 3.2.6 on 2022-06-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0004_shift_type_is_allow_in_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='img',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
