# Generated by Django 3.2.6 on 2022-06-23 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0006_leave_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_request',
            name='leave_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roster.shift_type'),
        ),
    ]
