# Generated by Django 3.2.6 on 2022-06-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0007_leave_request_leave_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_request',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Is Approved'),
        ),
    ]
