# Generated by Django 3.2.6 on 2022-06-23 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0011_auto_20220623_1012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave_request',
            old_name='approver_by',
            new_name='approver',
        ),
    ]
