# Generated by Django 3.2.6 on 2022-06-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0012_rename_approver_by_leave_request_approver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_request',
            name='is_rejected',
            field=models.BooleanField(default=False, verbose_name='Is Rejected'),
        ),
    ]
