# Generated by Django 3.2.6 on 2022-06-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0013_alter_leave_request_is_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift_type',
            name='is_leave',
            field=models.BooleanField(default=False),
        ),
    ]
