# Generated by Django 3.2.6 on 2022-06-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0014_shift_type_is_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_request',
            name='is_seen',
            field=models.BooleanField(default=False, verbose_name='Is Seen'),
        ),
        migrations.AddField(
            model_name='leave_request_comment',
            name='is_seen',
            field=models.BooleanField(default=False, verbose_name='Is Seen'),
        ),
    ]
