# Generated by Django 3.2.6 on 2022-06-25 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0015_auto_20220625_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_request_comment',
            name='comment_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_request_comment', to='roster.leave_request'),
        ),
    ]
