# Generated by Django 3.2.6 on 2022-06-25 12:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0016_alter_leave_request_comment_comment_for'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leave_request_comment',
            options={'verbose_name': 'Leave Request Comment', 'verbose_name_plural': 'Leave Request Comment'},
        ),
        migrations.AddField(
            model_name='leave_request',
            name='request_approved_on',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='leave_request',
            name='request_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
