# Generated by Django 3.2.6 on 2022-06-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0018_auto_20220626_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift_status',
            name='is_allow_use_by_members',
            field=models.BooleanField(default=False),
        ),
    ]
