# Generated by Django 3.2.6 on 2022-07-19 13:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roster', '0020_auto_20220719_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='change_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdate', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('is_seen', models.BooleanField(default=False, verbose_name='Is Seen')),
                ('request_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('request_approved_on', models.DateTimeField(default=None, null=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lr_approver_by_info', to=settings.AUTH_USER_MODEL)),
                ('change_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_from', to='roster.shift_type')),
                ('change_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_to', to='roster.shift_type')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lr_member_info', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roster.shift_status')),
            ],
            options={
                'verbose_name': 'Change Request',
                'verbose_name_plural': 'Change Request',
            },
        ),
        migrations.AlterModelOptions(
            name='shift_comment',
            options={'verbose_name': 'Shift Comments', 'verbose_name_plural': 'Shift Coments'},
        ),
        migrations.CreateModel(
            name='change_request_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1000)),
                ('is_seen', models.BooleanField(default=False, verbose_name='Is Seen')),
                ('comment_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comment_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_request_comment', to='roster.change_request')),
            ],
            options={
                'verbose_name': 'Change Request Comment',
                'verbose_name_plural': 'Change Request Comment',
            },
        ),
    ]
