# Generated by Django 3.2.6 on 2022-07-21 06:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roster', '0022_change_request_request_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='status_change_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdate', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('request_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('request_approved_on', models.DateTimeField(default=None, null=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lr_status_approver_by_info', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lr_status_member_info', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='roster.shift_status')),
                ('status_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_change_from', to='roster.shift_status')),
                ('status_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_change_to', to='roster.shift_status')),
            ],
            options={
                'verbose_name': 'Status change Request',
                'verbose_name_plural': 'Status change Request',
            },
        ),
        migrations.CreateModel(
            name='status_change_request_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1000)),
                ('is_seen', models.BooleanField(default=False, verbose_name='Is Seen')),
                ('comment_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comment_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_change_request_comment', to='roster.status_change_request')),
            ],
            options={
                'verbose_name': 'Status change Request Comment',
                'verbose_name_plural': 'Status change Request Comment',
            },
        ),
    ]
