# Generated by Django 3.2.6 on 2022-07-21 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0023_status_change_request_status_change_request_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status_change_request',
            name='status_from',
        ),
        migrations.RemoveField(
            model_name='status_change_request',
            name='status_to',
        ),
        migrations.AddField(
            model_name='status_change_request',
            name='shift_status_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_status_request', to='roster.shift_status'),
        ),
    ]
