# Generated by Django 3.2.6 on 2022-07-22 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roster', '0025_shift_swap'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='shift_swap',
            new_name='swap_request',
        ),
        migrations.CreateModel(
            name='swap_request_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1000)),
                ('is_seen', models.BooleanField(default=False, verbose_name='Is Seen')),
                ('comment_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comment_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_request_comment', to='roster.swap_request')),
            ],
            options={
                'verbose_name': 'Change Request Comment',
                'verbose_name_plural': 'Change Request Comment',
            },
        ),
    ]
