# Generated by Django 3.2.6 on 2022-07-25 07:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0026_auto_20220722_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swap_request',
            name='swap_date',
        ),
        migrations.RemoveField(
            model_name='swap_request',
            name='swap_shift',
        ),
        migrations.AddField(
            model_name='swap_request',
            name='swap_date_by',
            field=models.DateField(default=datetime.date.today, verbose_name='Swap Date By'),
        ),
        migrations.AddField(
            model_name='swap_request',
            name='swap_date_to',
            field=models.DateField(default=datetime.date.today, verbose_name='Swap Date To'),
        ),
        migrations.AddField(
            model_name='swap_request',
            name='swap_shift_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='swap_shift_info_by', to='roster.shift_type'),
        ),
        migrations.AddField(
            model_name='swap_request',
            name='swap_shift_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='swap_shift_info_to', to='roster.shift_type'),
        ),
    ]
