# Generated by Django 3.2.6 on 2022-07-25 07:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roster', '0027_auto_20220725_0724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swap_request',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='swap_request',
            name='swap_date_by',
        ),
        migrations.RemoveField(
            model_name='swap_request',
            name='swap_shift_by',
        ),
        migrations.AddField(
            model_name='swap_request',
            name='requested_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_from_info', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='swap_request',
            name='swap_date_from',
            field=models.DateField(default=datetime.date.today, verbose_name='Swap Date From'),
        ),
        migrations.AddField(
            model_name='swap_request',
            name='swap_shift_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='swap_shift_info_from', to='roster.shift_type'),
        ),
    ]
