# Generated by Django 3.2.6 on 2022-07-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0028_auto_20220725_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='swap_request',
            name='sm_approved_on',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
