# Generated by Django 3.2.6 on 2022-07-25 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0029_swap_request_sm_approved_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swap_request',
            name='is_approved_sm',
        ),
        migrations.AddField(
            model_name='swap_request',
            name='sm_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sm_status', to='roster.shift_status'),
        ),
    ]
