# Generated by Django 3.2.6 on 2022-09-10 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0030_auto_20220725_1044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='swap_request_comment',
            options={'verbose_name': 'Swap Request Comment', 'verbose_name_plural': 'Swap Request Comment'},
        ),
    ]
