# Generated by Django 3.2.6 on 2022-09-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0031_alter_swap_request_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift_type',
            name='claim_amount',
            field=models.IntegerField(default=0),
        ),
    ]
