# Generated by Django 3.2.6 on 2022-09-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0032_shift_type_claim_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shift_type',
            old_name='claim_amount',
            new_name='holiday_claim',
        ),
        migrations.AddField(
            model_name='shift_type',
            name='normal_claim',
            field=models.IntegerField(default=0),
        ),
    ]
