# Generated by Django 3.2.6 on 2022-08-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notification_events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventID', models.CharField(default='', max_length=18)),
                ('CustomerID', models.CharField(default='', max_length=30)),
                ('TenantID', models.CharField(default='', max_length=18)),
                ('BLDSystemRoleCode', models.CharField(default='', max_length=18)),
                ('Status', models.CharField(default='', max_length=18)),
                ('DataCenterID', models.CharField(default='', max_length=18)),
                ('TenantRole', models.CharField(default='', max_length=18)),
                ('CurrentTemplateName', models.CharField(default='', max_length=500)),
                ('EventName', models.CharField(default='', max_length=800)),
                ('JiraTicket', models.CharField(default='', max_length=250)),
                ('NTDBEmailStatus', models.CharField(default='', max_length=10)),
                ('Phase', models.CharField(default='', max_length=18)),
                ('BundleID', models.CharField(default='', max_length=18)),
                ('CreatedBy', models.CharField(default='', max_length=18)),
                ('StartDateTime', models.DateTimeField(null=True)),
                ('EndDateTime', models.DateTimeField(null=True)),
                ('NotificationType', models.CharField(default='', max_length=18)),
                ('ServiceStatus', models.CharField(default='', max_length=18)),
                ('CreationDateTime', models.DateTimeField(null=True)),
                ('NotificationID', models.CharField(default='', max_length=18)),
                ('NotificationSubType', models.CharField(default='', max_length=18)),
                ('SentToCustomerOn', models.CharField(default='', max_length=18)),
                ('EntityLastChangedOn', models.CharField(default='', max_length=18)),
            ],
        ),
    ]
