# Generated by Django 3.2.6 on 2022-08-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_notification_events_sid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification_events',
            name='EntityLastChangedOn',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='notification_events',
            name='SentToCustomerOn',
            field=models.DateTimeField(null=True),
        ),
    ]
