# Generated by Django 3.2.6 on 2022-08-02 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_auto_20220801_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification_events',
            name='CustomerName',
        ),
        migrations.RemoveField(
            model_name='notification_events',
            name='SID',
        ),
        migrations.RemoveField(
            model_name='notification_events',
            name='SystemNumber',
        ),
    ]
