# Generated by Django 3.2.6 on 2022-08-02 08:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_auto_20220802_0736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification_events',
            old_name='BLDSystemRoleCode',
            new_name='DataCenters',
        ),
        migrations.RenameField(
            model_name='notification_events',
            old_name='EntityLastChangedOn',
            new_name='EndDate',
        ),
        migrations.RenameField(
            model_name='notification_events',
            old_name='SentToCustomerOn',
            new_name='StartDate',
        ),
        migrations.RenameField(
            model_name='notification_events',
            old_name='DataCenterID',
            new_name='SystemRoles',
        ),
        migrations.RemoveField(
            model_name='notification_events',
            name='CustomerID',
        ),
        migrations.RemoveField(
            model_name='notification_events',
            name='NotificationID',
        ),
        migrations.RemoveField(
            model_name='notification_events',
            name='NotificationSubType',
        ),
        migrations.RemoveField(
            model_name='notification_events',
            name='TenantID',
        ),
        migrations.RemoveField(
            model_name='notification_events',
            name='TenantRole',
        ),
        migrations.RemoveField(
            model_name='notification_events',
            name='id',
        ),
        migrations.AddField(
            model_name='notification_events',
            name='CreatedViaAPI',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='notification_events',
            name='EndTime',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='notification_events',
            name='IsEndTimeRevised',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='notification_events',
            name='IsSLARelevant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification_events',
            name='IsServiceStatusRevised',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='notification_events',
            name='IsStartTimeRevised',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='notification_events',
            name='ObjectID',
            field=models.CharField(default=django.utils.timezone.now, max_length=600, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification_events',
            name='StartTime',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='notification_events',
            name='TestMode',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='notification_events',
            name='EventID',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.CreateModel(
            name='notification_tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerID', models.CharField(default='', max_length=30)),
                ('TenantID', models.CharField(default='', max_length=18)),
                ('BLDSystemRoleCode', models.CharField(default='', max_length=18)),
                ('Status', models.CharField(default='', max_length=18)),
                ('DataCenterID', models.CharField(default='', max_length=18)),
                ('TenantRole', models.CharField(default='', max_length=18)),
                ('ParentObjectID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_event_tenant_info', to='notification.notification_events')),
            ],
        ),
        migrations.CreateModel(
            name='notification_events_stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NotificationID', models.CharField(default='', max_length=18)),
                ('NotificationSubType', models.CharField(default='', max_length=18)),
                ('SentToCustomerOn', models.DateTimeField(null=True)),
                ('EntityLastChangedOn', models.DateTimeField(null=True)),
                ('ParentObjectID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_event_stage_info', to='notification.notification_events')),
            ],
        ),
    ]
