# Generated by Django 3.2.6 on 2022-08-02 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spc_cld', '0008_notification_service_status_notification_status'),
        ('notification', '0006_auto_20220802_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification_events',
            name='NotificationType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_type_info', to='spc_cld.notification_type'),
        ),
        migrations.AlterField(
            model_name='notification_events',
            name='ServiceStatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_service_status_info', to='spc_cld.notification_service_status'),
        ),
        migrations.AlterField(
            model_name='notification_events',
            name='Status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_status_info', to='spc_cld.notification_status'),
        ),
        migrations.AlterField(
            model_name='notification_events_stage',
            name='NotificationSubType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_subtype_info', to='spc_cld.notification_subtype'),
        ),
    ]
