# Generated by Django 3.2.6 on 2022-08-02 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spc_cld', '0008_notification_service_status_notification_status'),
        ('notification', '0007_auto_20220802_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification_tenant',
            name='BusinessType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noti_tenant_business_type_decs_re', to='spc_cld.tenant_business_type_decs'),
        ),
        migrations.AddField(
            model_name='notification_tenant',
            name='CustomerName',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='notification_tenant',
            name='DBSystemID',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='notification_tenant',
            name='LifeCycleStatus',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='notification_tenant',
            name='SID',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='notification_tenant',
            name='SystemCMPTemplateID',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='notification_tenant',
            name='SystemNumber',
            field=models.CharField(default='', max_length=18),
        ),
    ]
