# Generated by Django 3.2.6 on 2022-08-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0008_auto_20220802_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification_events',
            name='BundleID',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='notification_events',
            name='CreatedBy',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='notification_events',
            name='DataCenters',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='notification_events',
            name='Phase',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='notification_events',
            name='SystemRoles',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='notification_events_stage',
            name='NotificationID',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='notification_tenant',
            name='BLDSystemRoleCode',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='notification_tenant',
            name='DataCenterID',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='notification_tenant',
            name='Status',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='notification_tenant',
            name='SystemNumber',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='notification_tenant',
            name='TenantID',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='notification_tenant',
            name='TenantRole',
            field=models.CharField(default='', max_length=100),
        ),
    ]
