# Generated by Django 3.2.6 on 2022-08-03 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spc_cld', '0009_notification_phase'),
        ('notification', '0009_auto_20220802_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification_events',
            name='Phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_phase_info', to='spc_cld.notification_phase'),
        ),
    ]
