# Generated by Django 3.2.6 on 2022-08-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0010_alter_notification_events_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification_events',
            name='IsFianlRcaSlaExpired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification_events',
            name='IsFinalRcaSend',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification_events',
            name='IsFinalRcaSloExpired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification_events',
            name='IsInterRcaSend',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification_events',
            name='IsInterRcaSlaExpired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification_events',
            name='IsInterRcaSloExpired',
            field=models.BooleanField(default=False),
        ),
    ]
