# Generated by Django 3.2.6 on 2022-08-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0011_auto_20220804_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification_events_stage',
            name='isNotificationProcessed',
            field=models.BooleanField(default=False),
        ),
    ]
