# Generated by Django 3.2.6 on 2022-08-04 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0012_notification_events_stage_isnotificationprocessed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification_events',
            old_name='IsFianlRcaSlaExpired',
            new_name='IsFinalRcaSlaExpired',
        ),
    ]
