# Generated by Django 3.2.6 on 2022-08-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0013_rename_isfianlrcaslaexpired_notification_events_isfinalrcaslaexpired'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification_events',
            name='isProd',
            field=models.BooleanField(default=False),
        ),
    ]
