# Generated by Django 3.2.6 on 2022-11-14 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='master_tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ticket_ID', models.CharField(max_length=10)),
                ('Subject', models.TextField(null=True)),
                ('Action_Taken', models.TextField(null=True)),
                ('Action_Required', models.TextField(null=True)),
                ('Status', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField()),
                ('date', models.DateField(default=datetime.datetime(2022, 11, 14, 23, 4, 44, 438470))),
                ('shift', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='outage_master_tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ticket_ID', models.CharField(max_length=10)),
                ('Subject', models.CharField(max_length=100)),
                ('customer_impact', models.TextField()),
                ('Action_Required', models.TextField()),
                ('Status', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField()),
                ('date', models.DateField(default=datetime.datetime(2022, 11, 14, 23, 4, 44, 438470))),
                ('shift', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='outage_tracking_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ticket_ID', models.CharField(max_length=10)),
                ('Subject', models.CharField(max_length=100)),
                ('customer_impact', models.TextField()),
                ('Action_Required', models.TextField()),
                ('Status', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField()),
                ('date', models.DateField(default=datetime.date(2022, 11, 14))),
                ('shift', models.CharField(max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tickets_count_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('alerts', models.CharField(max_length=50)),
                ('manual_incidents', models.CharField(max_length=50)),
                ('problems', models.CharField(max_length=50)),
                ('service_request', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tickets_notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='tracking_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ticket_ID', models.CharField(max_length=10)),
                ('Subject', models.TextField(null=True)),
                ('Action_Taken', models.TextField(null=True)),
                ('Action_Required', models.TextField()),
                ('Status', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField()),
                ('date', models.DateField(default=datetime.datetime(2022, 11, 14, 23, 4, 44, 437470))),
                ('shift', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
