# Generated by Django 3.2.6 on 2022-11-20 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftpasstool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_type', models.CharField(choices=[('S4H', 'S4H'), ('IBP', 'IBP'), ('BYD/C4C', 'BYD/C4C')], default='S4H', max_length=20)),
                ('region', models.CharField(choices=[('EMEA', 'EMEA'), ('APJ', 'APJ'), ('AMER', 'AMER'), ('MENA', 'MENA'), ('OTHERS', 'OTHERS')], default='EMEA', max_length=20)),
                ('planned_start_date', models.DateTimeField()),
                ('planned_end_date', models.DateTimeField()),
                ('ticket_id', models.CharField(max_length=100, null=True)),
                ('subject', models.CharField(max_length=250, null=True)),
                ('pre_check_status', models.CharField(choices=[('In Progress', 'In Progress'), ('Waiting', 'Waiting'), ('Pending', 'Pending'), ('Completed', 'Completed')], default='In Progress', max_length=250)),
                ('comments', models.CharField(max_length=250, null=True)),
                ('cr_id', models.CharField(max_length=250, null=True)),
                ('cr_approval', models.CharField(choices=[('In Progress', 'In Progress'), ('Waiting', 'Waiting'), ('Pending', 'Pending'), ('Completed', 'Completed')], default='In Progress', max_length=250, null=True)),
                ('resource', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='master_tickets',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 20, 12, 30, 53, 368943)),
        ),
        migrations.AlterField(
            model_name='outage_master_tickets',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 20, 12, 30, 53, 368943)),
        ),
        migrations.AlterField(
            model_name='outage_tracking_history',
            name='date',
            field=models.DateField(default=datetime.date(2022, 11, 20)),
        ),
        migrations.AlterField(
            model_name='tracking_history',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 20, 12, 30, 53, 368943)),
        ),
    ]
