# Generated by Django 3.2.6 on 2023-03-27 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shiftpasstool', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sm_infra_activate',
            name='assigned',
        ),
    ]
