# Generated by Django 3.2.6 on 2023-02-11 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftpasstool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_tickets',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 2, 11, 22, 25, 4, 936855)),
        ),
        migrations.AlterField(
            model_name='outage_master_tickets',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 2, 11, 22, 25, 4, 937854)),
        ),
        migrations.AlterField(
            model_name='outage_tracking_history',
            name='Action_Required',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='outage_tracking_history',
            name='customer_impact',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='outage_tracking_history',
            name='date',
            field=models.DateField(default=datetime.date(2023, 2, 11)),
        ),
        migrations.AlterField(
            model_name='tracking_history',
            name='Action_Required',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tracking_history',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 2, 11, 22, 25, 4, 935858)),
        ),
    ]
