# Generated by Django 3.2.6 on 2022-11-20 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftpasstool', '0002_auto_20221120_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitydb',
            name='cr_approval',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Waiting', 'Waiting'), ('New', 'New'), ('Completed', 'Completed')], default='New', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='activitydb',
            name='planned_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activitydb',
            name='pre_check_status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Waiting', 'Waiting'), ('New', 'New'), ('Completed', 'Completed')], default='New', max_length=250),
        ),
        migrations.AlterField(
            model_name='master_tickets',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 20, 16, 20, 6, 583039)),
        ),
        migrations.AlterField(
            model_name='outage_master_tickets',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 20, 16, 20, 6, 583039)),
        ),
        migrations.AlterField(
            model_name='tracking_history',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 20, 16, 20, 6, 583039)),
        ),
    ]
