# Generated by Django 3.2.6 on 2023-03-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftpasstool', '0002_remove_sm_infra_activate_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitydb',
            name='assigned',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
