# Generated by Django 3.2.6 on 2023-02-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftpasstool', '0002_auto_20230211_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_tickets',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='outage_master_tickets',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='outage_tracking_history',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tracking_history',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
