# Generated by Django 3.2.6 on 2023-03-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftpasstool', '0003_activitydb_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitydb',
            name='remarks',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
