# Generated by Django 3.2.6 on 2023-04-06 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shiftpasstool', '0003_auto_20230213_1602'),
        ('shiftpasstool', '0004_auto_20230401_1310'),
    ]

    operations = [
    ]
