# Generated by Django 3.2.6 on 2022-11-26 06:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftpasstool', '0004_auto_20221120_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='sm_infra_activate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_start_date', models.DateTimeField()),
                ('planned_end_date', models.DateTimeField(blank=True, null=True)),
                ('subject', models.CharField(max_length=250, null=True)),
                ('pre_check_status', models.CharField(choices=[('Inprogress', 'Inprogress'), ('Waiting', 'Waiting'), ('New', 'New'), ('Resolved', 'Resolved')], default='New', max_length=250)),
                ('cr_id', models.CharField(max_length=250, null=True)),
                ('shift', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='activitydb',
            name='cr_approval',
            field=models.CharField(choices=[('Inprogress', 'Inprogress'), ('Waiting', 'Waiting'), ('New', 'New'), ('Resolved', 'Resolved')], default='New', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='activitydb',
            name='pre_check_status',
            field=models.CharField(choices=[('Inprogress', 'Inprogress'), ('Waiting', 'Waiting'), ('New', 'New'), ('Resolved', 'Resolved')], default='New', max_length=250),
        ),
        migrations.AlterField(
            model_name='master_tickets',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 26, 12, 4, 4, 986747)),
        ),
        migrations.AlterField(
            model_name='outage_master_tickets',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 26, 12, 4, 4, 986747)),
        ),
        migrations.AlterField(
            model_name='outage_tracking_history',
            name='date',
            field=models.DateField(default=datetime.date(2022, 11, 26)),
        ),
        migrations.AlterField(
            model_name='tracking_history',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 26, 12, 4, 4, 986747)),
        ),
    ]
