# Generated by Django 3.2.6 on 2023-03-31 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftpasstool', '0004_activitydb_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='sm_infra_activate',
            name='assigned',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='sm_infra_activate',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
