# Generated by Django 3.2.6 on 2022-11-26 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftpasstool', '0005_auto_20221126_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sm_infra_activate',
            old_name='cr_id',
            new_name='ticket_id',
        ),
        migrations.AlterField(
            model_name='master_tickets',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 26, 12, 27, 44, 672960)),
        ),
        migrations.AlterField(
            model_name='outage_master_tickets',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 26, 12, 27, 44, 673960)),
        ),
        migrations.AlterField(
            model_name='tracking_history',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 26, 12, 27, 44, 672960)),
        ),
    ]
