# Generated by Django 3.2.6 on 2023-04-22 17:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shiftpasstool', '0006_alter_activitydb_planned_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitydb',
            name='ticket_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sm_infra_activate',
            name='ticket_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
