# Generated by Django 3.2.6 on 2022-12-01 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftpasstool', '0007_auto_20221201_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitydb',
            name='floatingCmpDate',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='master_tickets',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 12, 1, 19, 41, 4, 284242)),
        ),
        migrations.AlterField(
            model_name='outage_master_tickets',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 12, 1, 19, 41, 4, 299869)),
        ),
        migrations.AlterField(
            model_name='tracking_history',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 12, 1, 19, 41, 4, 284242)),
        ),
    ]
