# Generated by Django 3.2.6 on 2023-04-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftpasstool', '0007_auto_20230422_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitydb',
            name='cr_approval',
            field=models.CharField(choices=[('Inprogress', 'Inprogress'), ('Waiting', 'Waiting'), ('New', 'New'), ('Resolved', 'Resolved')], default='New', max_length=250),
        ),
        migrations.AlterField(
            model_name='activitydb',
            name='cr_id',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activitydb',
            name='subject',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sm_infra_activate',
            name='assigned',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sm_infra_activate',
            name='floatingImplementation',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sm_infra_activate',
            name='remarks',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sm_infra_activate',
            name='shift',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
