# Generated by Django 3.2.6 on 2022-12-02 12:26

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shiftpasstool', '0008_auto_20221201_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitydb',
            name='pre_check_status_text',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activitydb',
            name='pre_check_status',
            field=models.CharField(default='New', max_length=250),
        ),
        migrations.AlterField(
            model_name='master_tickets',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 12, 2, 17, 56, 38, 550485)),
        ),
        migrations.AlterField(
            model_name='outage_master_tickets',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 12, 2, 17, 56, 38, 551482)),
        ),
        migrations.AlterField(
            model_name='outage_tracking_history',
            name='date',
            field=models.DateField(default=datetime.date(2022, 12, 2)),
        ),
        migrations.AlterField(
            model_name='tracking_history',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 12, 2, 17, 56, 38, 550485)),
        ),
    ]
