# Generated by Django 3.2.6 on 2022-12-10 19:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftpasstool', '0009_auto_20221202_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_tickets',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 12, 11, 1, 1, 34, 621587)),
        ),
        migrations.AlterField(
            model_name='outage_master_tickets',
            name='Subject',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='outage_master_tickets',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 12, 11, 1, 1, 34, 621587)),
        ),
        migrations.AlterField(
            model_name='outage_tracking_history',
            name='Subject',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='outage_tracking_history',
            name='date',
            field=models.DateField(default=datetime.date(2022, 12, 11)),
        ),
        migrations.AlterField(
            model_name='tracking_history',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 12, 11, 1, 1, 34, 620587)),
        ),
    ]
