# Generated by Django 3.2.6 on 2022-12-10 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftpasstool', '0010_auto_20221211_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_tickets',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 12, 11, 1, 7, 3, 68496)),
        ),
        migrations.AlterField(
            model_name='outage_master_tickets',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 12, 11, 1, 7, 3, 69496)),
        ),
        migrations.AlterField(
            model_name='tracking_history',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 12, 11, 1, 7, 3, 68496)),
        ),
    ]
