# Generated by Django 3.2.6 on 2023-01-08 05:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftpasstool', '0011_auto_20221211_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitydb',
            name='timerange',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outage_tracking_history',
            name='timerange',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sm_infra_activate',
            name='timerange',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tracking_history',
            name='timerange',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activitydb',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='activitydb',
            name='resource',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='activitydb',
            name='subject',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='master_tickets',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 8, 11, 0, 1, 426137)),
        ),
        migrations.AlterField(
            model_name='outage_master_tickets',
            name='Action_Required',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='outage_master_tickets',
            name='Subject',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='outage_master_tickets',
            name='customer_impact',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='outage_master_tickets',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 8, 11, 0, 1, 426137)),
        ),
        migrations.AlterField(
            model_name='outage_tracking_history',
            name='Subject',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='outage_tracking_history',
            name='date',
            field=models.DateField(default=datetime.date(2023, 1, 8)),
        ),
        migrations.AlterField(
            model_name='sm_infra_activate',
            name='floatingImplementation',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sm_infra_activate',
            name='subject',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tickets_notes',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tracking_history',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 8, 11, 0, 1, 426137)),
        ),
    ]
