# Generated by Django 3.2.6 on 2023-02-04 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shiftpasstool', '0012_auto_20230108_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_tickets',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 2, 4, 21, 2, 8, 325626)),
        ),
        migrations.AlterField(
            model_name='outage_master_tickets',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 2, 4, 21, 2, 8, 325626)),
        ),
        migrations.AlterField(
            model_name='outage_tracking_history',
            name='date',
            field=models.DateField(default=datetime.date(2023, 2, 4)),
        ),
        migrations.AlterField(
            model_name='tracking_history',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 2, 4, 21, 2, 8, 324623)),
        ),
    ]
