# Generated by Django 3.2.6 on 2022-09-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_availability', '0002_auto_20220924_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='Category',
            field=models.CharField(default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='EventID',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='OutageType',
            field=models.CharField(default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='ProblemTicket',
            field=models.CharField(default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='RCACategory',
            field=models.CharField(default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='SubCategory',
            field=models.CharField(default='', max_length=150, null=True),
        ),
    ]
