# Generated by Django 3.2.6 on 2022-09-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_availability', '0003_auto_20220924_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='ProblemTicket',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
