from django.db import models
from apps.spc_cld.models import notification_type, notification_subtype, notification_service_status, notification_status, tenant_business_type_decs, notification_phase

# Create your models here.
class notification_events(models.Model):
    ObjectID = models.CharField(max_length=600, primary_key=True)
    CreatedViaAPI = models.CharField(max_length=250, default='')
    CurrentTemplateName = models.CharField(max_length=500,default='')
    EventID = models.CharField(max_length=50,default='')
    EndDate = models.DateTimeField(null=True)
    EndTime = models.CharField(max_length=250, default='')
    EventName = models.CharField(max_length=800,default='')
    JiraTicket = models.CharField(max_length=250,default='')
    NTDBEmailStatus = models.CharField(max_length=10,default='')
    Phase = models.ForeignKey(notification_phase, related_name='notification_phase_info', on_delete=models.CASCADE, blank=True, null=True)
    StartDate = models.DateTimeField(null=True)
    StartTime = models.CharField(max_length=250, default='')
    TestMode = models.CharField(max_length=250, default='')
    BundleID = models.CharField(max_length=100,default='')
    CreatedBy = models.CharField(max_length=100,default='')
    StartDateTime = models.DateTimeField(null=True)
    EndDateTime = models.DateTimeField(null=True)
    NotificationType = models.ForeignKey(notification_type, related_name='notification_type_info', on_delete=models.CASCADE, blank=True, null=True)
    Status = models.ForeignKey(notification_status, related_name='notification_status_info', on_delete=models.CASCADE, blank=True, null=True)
    SystemRoles = models.CharField(max_length=100, default='')
    ServiceStatus = models.ForeignKey(notification_service_status, related_name='notification_service_status_info', on_delete=models.CASCADE, blank=True, null=True)
    CreationDateTime = models.DateTimeField(null=True)
    DataCenters = models.CharField(max_length=100,default='')
    IsStartTimeRevised = models.CharField(max_length=200, default='')
    IsSLARelevant = models.BooleanField(default=False)
    IsServiceStatusRevised = models.CharField(max_length=200, default='')
    IsEndTimeRevised = models.CharField(max_length=200, default='')
    IsInterRcaSloExpired = models.BooleanField(default=False)
    IsInterRcaSlaExpired = models.BooleanField(default=False)
    IsFinalRcaSloExpired = models.BooleanField(default=False)
    IsFinalRcaSlaExpired = models.BooleanField(default=False)
    IsInterRcaSend = models.BooleanField(default=False)
    IsFinalRcaSend = models.BooleanField(default=False)
    isProd = models.BooleanField(default=False)

class notification_events_stage(models.Model):
    ParentObjectID = models.ForeignKey(notification_events, related_name='notification_event_stage_info', on_delete=models.CASCADE, blank=True, null=True)
    NotificationID = models.CharField(max_length=100,default='')
    NotificationSubType = models.ForeignKey(notification_subtype, related_name='notification_subtype_info', on_delete=models.CASCADE, blank=True, null=True)
    SentToCustomerOn = models.DateTimeField(null=True)
    EntityLastChangedOn = models.DateTimeField(null=True)
    isNotificationProcessed = models.BooleanField(default=False)

class notification_tenant(models.Model):
    ParentObjectID = models.ForeignKey(notification_events, related_name='notification_event_tenant_info', on_delete=models.CASCADE, blank=True, null=True)
    CustomerID = models.CharField(max_length=30,default='')
    CustomerName = models.CharField(max_length=255,default='')
    TenantID = models.CharField(max_length=100,default='')
    SystemNumber = models.CharField(max_length=100,default='')
    SID = models.CharField(max_length=40,default='')
    DBSystemID = models.CharField(max_length=64,default='')
    LifeCycleStatus = models.CharField(max_length=10,default='')
    BusinessType = models.ForeignKey(tenant_business_type_decs, related_name='noti_tenant_business_type_decs_re', on_delete=models.CASCADE,blank=True, null=True)
    BLDSystemRoleCode = models.CharField(max_length=100,default='')
    Status = models.CharField(max_length=100,default='')
    DataCenterID = models.CharField(max_length=100,default='')
    SystemCMPTemplateID = models.CharField(max_length=64,default='')
    TenantRole = models.CharField(max_length=100,default='')
