# Generated by Django 3.2.6 on 2022-05-19 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='application_dr_type_collection_decs',
            fields=[
                ('code', models.CharField(default='', max_length=64, primary_key=True, serialize=False)),
                ('description', models.CharField(default='', max_length=164)),
            ],
            options={
                'verbose_name': 'Application DR Type',
                'verbose_name_plural': 'Application DR Type',
            },
        ),
        migrations.CreateModel(
            name='application_ha_type_collection_decs',
            fields=[
                ('code', models.CharField(default='', max_length=64, primary_key=True, serialize=False)),
                ('description', models.CharField(default='', max_length=164)),
            ],
            options={
                'verbose_name': 'Application HR Type',
                'verbose_name_plural': 'Application HR Type',
            },
        ),
        migrations.CreateModel(
            name='database_dr_type_collection_decs',
            fields=[
                ('code', models.CharField(default='', max_length=64, primary_key=True, serialize=False)),
                ('description', models.CharField(default='', max_length=164)),
            ],
            options={
                'verbose_name': 'Database DR Type',
                'verbose_name_plural': 'Database DR Type',
            },
        ),
        migrations.CreateModel(
            name='database_ha_type_collection_decs',
            fields=[
                ('code', models.CharField(default='', max_length=64, primary_key=True, serialize=False)),
                ('description', models.CharField(default='', max_length=164)),
            ],
            options={
                'verbose_name': 'Database HR Type',
                'verbose_name_plural': 'Database HR Type',
            },
        ),
        migrations.CreateModel(
            name='datacenter_decs',
            fields=[
                ('code', models.CharField(default='', max_length=64, primary_key=True, serialize=False)),
                ('infra', models.CharField(default='', max_length=64)),
                ('region', models.CharField(default='', max_length=64)),
                ('is_used', models.BooleanField(default=False)),
                ('description', models.CharField(default='', max_length=164)),
            ],
            options={
                'verbose_name': 'Datacenter',
                'verbose_name_plural': 'Datacenter',
            },
        ),
        migrations.CreateModel(
            name='system',
            fields=[
                ('SID', models.CharField(default='', max_length=40)),
                ('SystemNumber', models.CharField(default='', max_length=18, primary_key=True, serialize=False)),
                ('SystemRole', models.CharField(default='', max_length=30)),
                ('LifeCycleStatus', models.CharField(default='', max_length=10)),
                ('NetworkSegmentID', models.CharField(default='', max_length=80)),
                ('LeadingProductPPMS', models.CharField(default='', max_length=20)),
                ('LeadingProductVersionPPMS', models.CharField(default='', max_length=20)),
                ('HasSharedDBTenant', models.BooleanField(default=False)),
                ('IsDbShared', models.BooleanField(default=False)),
                ('ExternalD', models.CharField(default='', max_length=200)),
                ('EUAccess', models.BooleanField(default=False)),
                ('DatabaseHostFQDN', models.CharField(default='', max_length=255)),
                ('DatabaseHost', models.CharField(default='', max_length=65)),
                ('WebdispatcherFarmName', models.CharField(default='', max_length=255)),
                ('ApplicationHost', models.CharField(default='', max_length=64)),
                ('ApplicationHostFQDN', models.CharField(default='', max_length=255)),
                ('LeadingProductName', models.CharField(default='', max_length=120)),
                ('LeadingProductPatchVersion', models.BigIntegerField(default=0)),
                ('LeadingProductSoftwareType', models.CharField(default='', max_length=12)),
                ('LeadingProductSupportPackage', models.BigIntegerField(default=0)),
                ('LeadingProductVersionNumber', models.BigIntegerField(default=0)),
                ('DBSystemID', models.CharField(default='', max_length=40)),
                ('CMPTemplateID', models.CharField(default='', max_length=20)),
                ('CMPTime', models.CharField(default='', max_length=255)),
                ('InfrastructureProvider', models.CharField(default='', max_length=10)),
                ('CustomerID', models.CharField(default='', max_length=10)),
                ('CustomerName', models.CharField(default='', max_length=255)),
                ('InfrastructureType', models.CharField(default='', max_length=20)),
                ('CustomerTenantMainURL', models.CharField(default='', max_length=255)),
                ('DRActiveSystem', models.BooleanField(default=False)),
                ('DRSystemType', models.CharField(default='', max_length=30)),
                ('DRSystemNumber', models.CharField(default='', max_length=18)),
                ('HAActiveSystem', models.BooleanField(default=False)),
                ('HASystemType', models.CharField(default='', max_length=30)),
                ('HASystemNumber', models.CharField(default='', max_length=18)),
                ('CreationDateTime', models.DateTimeField(null=True)),
                ('EntityLastChangedOn', models.DateTimeField(null=True)),
                ('ApplicationDRType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_dr_type_collection_decs_re', to='spc_cld.application_dr_type_collection_decs')),
                ('ApplicationHAType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='application_ha_type_collection_decs_re', to='spc_cld.application_ha_type_collection_decs')),
            ],
            options={
                'ordering': ['DBSystemID'],
            },
        ),
        migrations.CreateModel(
            name='system_business_type_decs',
            fields=[
                ('code', models.CharField(default='', max_length=64, primary_key=True, serialize=False)),
                ('description', models.CharField(default='', max_length=164)),
            ],
            options={
                'verbose_name': 'System Business Type',
                'verbose_name_plural': 'System Business Types',
            },
        ),
        migrations.CreateModel(
            name='tenant_business_type_decs',
            fields=[
                ('code', models.CharField(default='', max_length=64, primary_key=True, serialize=False)),
                ('description', models.CharField(default='', max_length=164)),
            ],
            options={
                'verbose_name': 'Tenant Business Type',
                'verbose_name_plural': 'Tenant Business Types',
            },
        ),
        migrations.CreateModel(
            name='tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ObjectID', models.CharField(default='', max_length=250)),
                ('SystemNumber', models.CharField(default='', max_length=18)),
                ('SystemRole', models.CharField(default='', max_length=30)),
                ('ExternalID', models.CharField(default='', max_length=200)),
                ('SystemLifeCycleStatus', models.CharField(default='', max_length=10)),
                ('EUDataProtectionIndicator', models.BooleanField(default=False)),
                ('NetworkSegmentID', models.CharField(default='', max_length=80)),
                ('VersionNumber', models.BigIntegerField(default=0)),
                ('SupportPackage', models.BigIntegerField(default=0)),
                ('PatchVersion', models.BigIntegerField(default=0)),
                ('MainURL', models.CharField(default='', max_length=255)),
                ('HasSharedDBTenant', models.BooleanField(default=False)),
                ('CustomerID', models.CharField(default='', max_length=60)),
                ('CustomerName', models.CharField(default='', max_length=255)),
                ('DBSystemID', models.CharField(default='', max_length=64)),
                ('SystemDBHostFQDN', models.CharField(default='', max_length=255)),
                ('SystemWebdispatcherFarmName', models.CharField(default='', max_length=64)),
                ('SystemCMPTemplateID', models.CharField(default='', max_length=64)),
                ('SystemInfrastructureType', models.CharField(default='', max_length=64)),
                ('SID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SystemDetails_Tenant', to='spc_cld.system')),
                ('SystemBusinessType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tnt_system_business_type_decs_re', to='spc_cld.system_business_type_decs')),
                ('SystemLocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tnt_datacenter_decs_re', to='spc_cld.datacenter_decs')),
                ('TenantBusinessType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tnt_tenant_business_type_decs_re', to='spc_cld.tenant_business_type_decs')),
            ],
            options={
                'ordering': ['SID'],
            },
        ),
        migrations.AddField(
            model_name='system',
            name='BusinessType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_business_type_decs_re', to='spc_cld.system_business_type_decs'),
        ),
        migrations.AddField(
            model_name='system',
            name='DataBaseDRType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='database_dr_type_collection_decs_re', to='spc_cld.database_dr_type_collection_decs'),
        ),
        migrations.AddField(
            model_name='system',
            name='DataBaseHAType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='database_ha_type_collection_decs_re', to='spc_cld.database_ha_type_collection_decs'),
        ),
        migrations.AddField(
            model_name='system',
            name='DataCenterID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datacenter_decs_re', to='spc_cld.datacenter_decs'),
        ),
        migrations.CreateModel(
            name='host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InstanceType', models.CharField(default='', max_length=10)),
                ('InstanceNumber', models.CharField(default='', max_length=2)),
                ('InstanceName', models.CharField(default='', max_length=64)),
                ('HostName', models.CharField(default='', max_length=64)),
                ('LifeCycleStatus', models.CharField(default='', max_length=10)),
                ('SystemID', models.CharField(default='', max_length=40)),
                ('SystemNumber', models.CharField(default='', max_length=18)),
                ('CPUCount', models.IntegerField(default=0)),
                ('SystemMemory', models.IntegerField(default=0)),
                ('SystemOSName', models.CharField(default='', max_length=40)),
                ('SystemOSRelease', models.CharField(default='', max_length=60)),
                ('SystemOSType', models.CharField(default='', max_length=40)),
                ('SystemOSVersion', models.CharField(default='', max_length=256)),
                ('SystemType', models.CharField(default='', max_length=20)),
                ('SystemExternalStatus', models.CharField(default='', max_length=40)),
                ('SystemHypervisor', models.CharField(default='', max_length=100)),
                ('SystemHypervisorServerName', models.CharField(default='', max_length=64)),
                ('ComputerSystemPool', models.CharField(default='', max_length=255)),
                ('ComputerSystemResourcePool', models.CharField(default='', max_length=255)),
                ('ComputerSystemUsageArea', models.CharField(default='', max_length=255)),
                ('ComputerSystemCreationDateTime', models.DateTimeField(null=True)),
                ('ComputerSystemLastChangeDateTime', models.DateTimeField(null=True)),
                ('ComputerSystemVMFlavor', models.CharField(default='', max_length=255)),
                ('ComputerSystemDataCenterID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='host_datacenter_decs_re', to='spc_cld.datacenter_decs')),
                ('SID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SystemDetails', to='spc_cld.system')),
            ],
            options={
                'ordering': ['SID'],
            },
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['SID'], name='spc_cld_ten_SID_id_509302_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['DBSystemID'], name='spc_cld_ten_DBSyste_9ec1e5_idx'),
        ),
        migrations.AddIndex(
            model_name='system',
            index=models.Index(fields=['SID'], name='spc_cld_sys_SID_7e3319_idx'),
        ),
        migrations.AddIndex(
            model_name='system',
            index=models.Index(fields=['DBSystemID'], name='spc_cld_sys_DBSyste_8e1701_idx'),
        ),
        migrations.AddIndex(
            model_name='host',
            index=models.Index(fields=['HostName'], name='spc_cld_hos_HostNam_7d8a7d_idx'),
        ),
        migrations.AddIndex(
            model_name='host',
            index=models.Index(fields=['SID'], name='spc_cld_hos_SID_id_521082_idx'),
        ),
    ]
