# Generated by Django 3.2.6 on 2022-05-19 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spc_cld', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='system',
            unique_together={('SystemNumber', 'LifeCycleStatus')},
        ),
    ]
