# Generated by Django 3.2.6 on 2022-08-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spc_cld', '0004_auto_20220713_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='TenantID',
            field=models.CharField(default='', max_length=18),
        ),
    ]
