# Generated by Django 3.2.6 on 2022-08-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spc_cld', '0006_notification_subtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification_type',
            fields=[
                ('code', models.CharField(default='', max_length=64, primary_key=True, serialize=False)),
                ('description', models.CharField(default='', max_length=164)),
            ],
            options={
                'verbose_name': 'Notification Type',
                'verbose_name_plural': 'Notification Type',
            },
        ),
    ]
