# Generated by Django 3.2.6 on 2022-08-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spc_cld', '0007_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification_service_status',
            fields=[
                ('code', models.CharField(default='', max_length=64, primary_key=True, serialize=False)),
                ('description', models.CharField(default='', max_length=164)),
            ],
            options={
                'verbose_name': 'Notification Service Status',
                'verbose_name_plural': 'Notification Service Status',
            },
        ),
        migrations.CreateModel(
            name='notification_status',
            fields=[
                ('code', models.CharField(default='', max_length=64, primary_key=True, serialize=False)),
                ('description', models.CharField(default='', max_length=164)),
            ],
            options={
                'verbose_name': 'Notification Status',
                'verbose_name_plural': 'Notification Status',
            },
        ),
    ]
