# Generated by Django 3.2.6 on 2022-08-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spc_cld', '0008_notification_service_status_notification_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification_phase',
            fields=[
                ('code', models.CharField(default='', max_length=64, primary_key=True, serialize=False)),
                ('description', models.CharField(default='', max_length=164)),
            ],
            options={
                'verbose_name': 'Notification Phase',
                'verbose_name_plural': 'Notification Phase',
            },
        ),
    ]
