# Generated by Django 3.2.6 on 2022-08-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spc_cld', '0009_notification_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='AllocationLimit',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='system',
            name='EligibleDBSize',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='system',
            name='HostDBSize',
            field=models.CharField(default='', max_length=80),
        ),
    ]
