# Generated by Django 3.2.6 on 2022-08-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spc_cld', '0011_auto_20220829_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='AllocationLimit',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='tenant',
            name='CPU',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='tenant',
            name='MaximumConcurrentCPU',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='tenant',
            name='memory',
            field=models.CharField(default='', max_length=80),
        ),
    ]
