# Generated by Django 3.2.6 on 2022-09-17 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spc_cld', '0013_dr_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DR_CUSTOMER',
            new_name='dr_systems',
        ),
    ]
