# Generated by Django 3.2.6 on 2022-09-19 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spc_cld', '0015_alter_dr_systems_primarydc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dr_systems',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='dr_systems',
            name='isactive',
        ),
    ]
