# Generated by Django 3.2.6 on 2022-09-19 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spc_cld', '0016_auto_20220919_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='dr_systems',
            name='SystemRole',
            field=models.CharField(default='', max_length=30),
        ),
    ]
