# Generated by Django 3.2.6 on 2022-05-20 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pingdom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SID', models.CharField(max_length=3, null=True)),
                ('DC', models.CharField(max_length=3, null=True)),
                ('comment', models.TextField(null=True)),
                ('expry_date', models.DateTimeField(null=True)),
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('comment_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='URLComments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ('SID',),
            },
        ),
        migrations.AddIndex(
            model_name='comment_table',
            index=models.Index(fields=['SID'], name='pingdom_com_SID_a195ea_idx'),
        ),
    ]
