# Generated by Django 3.2.6 on 2022-05-21 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pingdom', '0002_auto_20220520_1337'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment_table',
            unique_together={('SID', 'DC')},
        ),
    ]
