# Generated by Django 3.2.6 on 2022-05-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingdom', '0005_pingdom_time_series_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pingdom_status',
            options={'ordering': ('SID',), 'verbose_name': 'Pingdom Status', 'verbose_name_plural': 'Pingdom Status'},
        ),
        migrations.AlterModelOptions(
            name='pingdom_time_series_data',
            options={'ordering': ('SID',), 'verbose_name': 'Pingdom Time Series', 'verbose_name_plural': 'Pingdom Time Series'},
        ),
        migrations.AlterField(
            model_name='pingdom_time_series_data',
            name='IsAcknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pingdom_time_series_data',
            name='ToTime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddIndex(
            model_name='pingdom_time_series_data',
            index=models.Index(fields=['SID'], name='pingdom_pin_SID_c71189_idx'),
        ),
    ]
