# Generated by Django 3.2.6 on 2022-08-01 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spc_cld', '0005_tenant_tenantid'),
        ('pingdom', '0009_rename_systemnumber_pingdom_time_series_data_systemnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pingdom_status',
            name='dc_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dc_info', to='spc_cld.datacenter_decs'),
        ),
        migrations.AlterField(
            model_name='pingdom_status',
            name='system_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sid_info', to='spc_cld.system'),
        ),
    ]
