# Generated by Django 3.2.6 on 2022-09-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingdom', '0011_auto_20220826_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='pingdom_time_series_data',
            name='BusinessType',
            field=models.CharField(default='', max_length=50),
        ),
    ]
