# Generated by Django 3.2.6 on 2021-10-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0003_rename_roles_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='not_from_cam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='technical_user',
            field=models.BooleanField(default=False),
        ),
    ]
