# Generated by Django 3.2.6 on 2021-10-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0004_auto_20211015_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='not_from_cam',
        ),
        migrations.AddField(
            model_name='user',
            name='cam',
            field=models.BooleanField(default=True),
        ),
    ]
