# Generated by Django 3.2.6 on 2021-10-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0006_user_is_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_block',
            field=models.BooleanField(default=False, verbose_name='block'),
        ),
    ]
