# Generated by Django 3.2.6 on 2021-10-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0007_alter_user_is_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='technical_user',
            field=models.BooleanField(default=False, help_text='Designates whether the user can use API.'),
        ),
    ]
