# Generated by Django 3.2.6 on 2021-10-26 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0009_auto_20211020_2249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subteam',
            options={'verbose_name': 'Sub-Team', 'verbose_name_plural': 'Sub-Teams'},
        ),
    ]
