# Generated by Django 3.2.6 on 2022-03-09 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0010_alter_subteam_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
