# Generated by Django 3.2.6 on 2022-03-10 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0014_sub_team_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sub_team_owner',
            options={'verbose_name': 'Sub-Team-Owner', 'verbose_name_plural': 'Sub-Team-Owners'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('TeamMember', 'Team Member can access all the pages in Hound'),)},
        ),
    ]
