# Generated by Django 3.2.6 on 2022-03-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0016_auto_20220310_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_access',
            name='id',
        ),
        migrations.AlterField(
            model_name='custom_access',
            name='url_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
