# Generated by Django 3.2.6 on 2022-03-10 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0017_auto_20220310_1559'),
    ]

    operations = [
        migrations.DeleteModel(
            name='custom_access',
        ),
    ]
