# Generated by Django 3.2.6 on 2022-03-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0019_custom_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_access',
            name='access_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='custom_access',
            name='space_name',
            field=models.CharField(max_length=100),
        ),
    ]
