# Generated by Django 3.2.6 on 2022-03-10 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user_account', '0020_auto_20220310_1639'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='custom_access',
            new_name='block_access',
        ),
    ]
