# Generated by Django 3.2.6 on 2022-03-10 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0021_rename_custom_access_block_access'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block_access',
            options={'permissions': (('team_member', 'Team_Member access role'),)},
        ),
    ]
