# Generated by Django 3.2.6 on 2022-03-10 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0024_alter_block_access_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block_access',
            options={'permissions': (('team_member', 'team_member'),)},
        ),
    ]
