# Generated by Django 3.2.6 on 2022-03-11 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0027_rename_block_access_page_access'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page_access',
            options={'permissions': (('team_member_cust', 'Default access for team member'), ('limited_access_cust', 'Default access for non-team member'))},
        ),
    ]
