# Generated by Django 3.2.6 on 2022-03-11 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user_account', '0028_alter_page_access_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page_access',
            name='access_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_name_ref', to='auth.permission'),
        ),
    ]
