# Generated by Django 3.2.6 on 2022-03-11 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0030_auto_20220311_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page_access',
            options={'permissions': (('team_member_cust', 'Default access for team member'), ('limited_access_cust', 'Default access for non-team member'), ('tenant_list_view', 'Access to view the tenant view'))},
        ),
    ]
