# Generated by Django 3.2.6 on 2022-03-11 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0031_alter_page_access_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page_access',
            options={'permissions': (('team_member_cust', 'Custom: Default access for team member'), ('limited_access_cust', 'Custom: Default access for non-team member'), ('tenant_list_view_cust', 'Custom: Access to view the tenant view'))},
        ),
    ]
