# Generated by Django 3.2.6 on 2022-03-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0032_alter_page_access_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='page_access',
            name='is_all_access',
            field=models.BooleanField(default=False, help_text='If True allow anyone to access this page.', verbose_name='Allow Everyone'),
        ),
    ]
