# Generated by Django 3.2.6 on 2022-03-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0034_alter_page_access_access_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deactivated_on',
            field=models.DateField(blank=True, default='9999-01-01', null=True, verbose_name='Deactivated on'),
        ),
    ]
