# Generated by Django 3.2.6 on 2022-05-14 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0036_alter_page_access_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page_access',
            old_name='is_all_access',
            new_name='is_allow_everyone',
        ),
    ]
