# Generated by Django 3.2.6 on 2022-05-16 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0037_rename_is_all_access_page_access_is_allow_everyone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page_access',
            options={'permissions': (('team_member_cust', 'Custom: Default access for team member'), ('limited_access_cust', 'Custom: Default access for non-team member'), ('tenant_list_view_cust', 'Custom: Access to view the tenant view'), ('modify_pingdom_access', 'Custom: User can modify the pingdom check name'), ('get_dc_info', 'Custom: User can view the system related info in Pingdom dashboard'))},
        ),
    ]
