# Generated by Django 3.2.6 on 2022-05-28 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0040_alter_page_access_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='page_access',
            unique_together={('url_name', 'space_name', 'request_method')},
        ),
    ]
