# Generated by Django 3.2.6 on 2022-06-03 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0041_alter_page_access_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roleTeam', to='user_account.team'),
        ),
        migrations.AlterField(
            model_name='subteam',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subteam_team', to='user_account.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teamLocation', to='user_account.location'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userRole', to='user_account.role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sub_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subteam', to='user_account.subteam'),
        ),
        migrations.AlterField(
            model_name='user',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userteam', to='user_account.team'),
        ),
    ]
