# Generated by Django 3.2.6 on 2022-06-03 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0045_auto_20220603_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page_access',
            options={'permissions': (('shift_planner', 'Custom: User can plan the shift'), ('team_member_cust', 'Custom: Default access for team member'), ('limited_access_cust', 'Custom: Default access for non-team member'), ('tenant_list_view_cust', 'Custom: Access to view the tenant view'), ('modify_pingdom_access', 'Custom: User can modify the pingdom check name'), ('get_dc_info', 'Custom: User can view the system related info in Pingdom dashboard'), ('acknowledge_downtime_access', 'Custom: User can acknowledge downtime'), ('view_acknowledge_downtime_access', 'Custom: User can view acknowledge downtime'))},
        ),
    ]
