# Generated by Django 3.2.6 on 2022-06-15 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0046_alter_page_access_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page_access',
            options={'permissions': (('shift_planner', 'Custom: User can plan the shift'), ('team_member', 'Custom: Default access for team member'), ('has_access', 'Custom: Default access for CAM user outside operation team'), ('limited_access_cust', 'Custom: Default access for non-team member'), ('modify_pingdom_access', 'Custom: User can modify the pingdom check name'), ('get_dc_info', 'Custom: User can view the system related info in Pingdom dashboard'), ('acknowledge_downtime_access', 'Custom: User can acknowledge downtime'), ('view_acknowledge_downtime_access', 'Custom: User can view acknowledge downtime'))},
        ),
    ]
