# Generated by Django 3.2.6 on 2022-06-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0047_alter_page_access_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subteam',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
