# Generated by Django 3.2.6 on 2022-09-10 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0053_change_work_group_request'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='change_work_group_request',
            options={'verbose_name': 'Work Group Request', 'verbose_name_plural': 'Work Group Request'},
        ),
        migrations.AddField(
            model_name='change_work_group_request',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_by_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
