# Generated by Django 3.2.6 on 2022-09-10 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0054_auto_20220910_0650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='change_work_group_request',
            name='current',
        ),
        migrations.AddField(
            model_name='change_work_group_request',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_subteam_info', to='user_account.subteam'),
        ),
    ]
