# Generated by Django 3.2.6 on 2023-01-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='release_notification',
            name='app_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
